### ISSUE TITLE
Android sliter med embedded video

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMTV#21]
"Error loading media: File could not be played"

Martin har hatt trøbbel, testa med OnePlus 7 Pro og Samsung S8 med Chrome.

**Comment by AsgeirSH** [comment]
Gjelder video i https://ukm.no/moreogromsdal/2020/12/08/digital-ukm/

**Comment by martingiskegjerde** [comment]
Får ikke spilt av video embedded i toppen, eller den her https://tv.ukm.no/Digital-fylkesfestival-UKM-Mre-og-Romsdal/14961

Men får spilt av denne i brødteksten fra OP7 Pro i Chrome https://ukm.no/moreogromsdal/2020/12/08/digital-ukm/
Ingen av videoene funker i Facebook-nettleser på Android (OP7P og S8)

**Comment by martingiskegjerde** [comment]
**Mindre:**

![Screenshot_20201209-131220](https://user-images.githubusercontent.com/75684240/101628553-4a9b7a80-3a20-11eb-8d03-5ab9e3d7ef5d.jpg)

**Fullskjerm:**
![Screenshot_20201209-131211](https://user-images.githubusercontent.com/75684240/101628559-4b341100-3a20-11eb-9639-9dfca3602665.jpg)

Fullskjerm fyller også bare embedded vinduet mer (fullskjerm) eller mindre.

OnePlus 7 Pro.

**Comment by mariusmandal** [comment]
Fixed 🎉  Men ikke player controls (det ligger i eget issue)
