### ISSUE TITLE
Cron-jobber må korrigeres

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMTV#9]
- [ ] Sync-jobben fungerer ikke
- [ ] Tags-jobben må kunne kjøres med ett kall (og ikke 15 som den må aws..)

**Comment by mariusmandal** [comment]
OptionBundle må skrive til fil, eller ha samme tabell i UKMss3 (som jeg er litt redd for - må dobbeltsjekke bundlenames++ først ) da doctrine bruker SS3-tilkobling

**Comment by AsgeirSH** [comment]
TODO: Sjekk om fiksen funker.

**Comment by mariusmandal** [comment]
Booyah!

## API: 
mulig å deaktivere error-logging 
https://github.com/UKMNorge/UKMapi/commit/34b74b995cba2ff1cffc6e2b9bc8f0055d3ef2b8
(spammy da cron-jobbene "misbruker" insert og unique-constraints heller enn å selecte og update

unngå !isset-notifications/feil 
https://github.com/UKMNorge/UKMapi/commit/f569a028081e690e374f93c24fc823ee08025d4b

## UKMtv
Legg til pagination, fix mindre unset-notifications
7757778e77edad4421e39e6374626b057c290cee
b8ed7d2472679f2d6f57a4a3f16e52dee78eac4e
9cd90a3ea55090c01b7fb6ed6f4ae9a45a0680c2
f55a08b9a7f8916c13ad6113237a78eee092940f
1e4a32719606811650b2650696b432481265435b
3f085da7c7160257322e629860ea8d55bf972c09
e2451e72cf9089fa3560ecec4fc30a6ed2086034
41ea448cff0c9af811a0b4ebd30effc4a69063ee

**Comment by AsgeirSH** [comment]
Go to bed!
